version: "3.8"

services:
  myapp:
    container_name: doc-to-pdf-service
    build: .
    ports:
      - "9091:9091"
    networks:
      myapp_network:
        ipv4_address: 192.168.1.100

networks:
  myapp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
